name: Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run ruff
        run: |
          poetry run pre-commit run -a 

  run-tests:
    needs: code-quality    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run all tests with pytest
        run: |
          poetry run pytest --cov --cov-report=xml:coverage_report.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage_report.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
